services:
  streamlit:
    build: ./src/app
    ports:
      - "8501:8501"
    volumes:
      - streamlit_data:/home/app/data
    environment:
      - PORT=8501
    restart: unless-stopped
  api:
    build: ./src/api
    expose:
      - "8000"
    environment:
      - PORT=8000
    restart: unless-stopped

volumes:
  streamlit_data: