services:
  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    depends_on:
      - streamlit
    restart: unless-stopped

  streamlit:
    build:
      context: .
      dockerfile: src/app/Dockerfile
    expose:
      - "8501"
    environment:
      - API_URL=http://api:8000    # "api" = nom du service, résolu automatiquement
    volumes:
      - streamlit_data:/home/app/data
    restart: unless-stopped

  api:
    build:
      context: .                    # racine du projet, englobe tout src/
      dockerfile: src/api/Dockerfile
    environment:
      - MLFLOW_TRACKING_URI=http://13.37.240.162:5000
    expose:
      - "8000"
    restart: unless-stopped

volumes:
  streamlit_data:
  caddy_data: