api:
  piezometer:
    provider: "hubeau"
    url_station: "https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/stations"
    url_piezometre: "https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/chroniques"
    code_bss: 
      - "10906X0039/C2-1"
  weather:
    provider: "open-meteo"
    url_archive: "https://archive-api.open-meteo.com/v1/archive"
    url_forecast: ""
    start_date: "2017-01-01"
    
paths:
  data:
    raw: "data/raw"
    interim: "data/interim"
    processed: "data/processed"
    external: "data/external"
  interim_filename: "dataset_interim" 
  processed_filename: "dataset_processed"
  weather:
    raw_filename: "weather_raw"
    interim_filename: "weather_cleaned"
  station:
    raw_filename: "station_raw"
  piezometer:
    raw_filename: "piezometer_raw"
    interim_filename: "piezometer_cleaned"
  model_filename: "model.joblib"
  predictions_filename: "reports/predictions"
  
s3:
  bucket: "nappecast"
  prefixes:
    processed: "data/processed"
    interim: "data/interim"
    raw: "data/raw"
    external: "data/external"

model:
  type: ""
  params:
    random_state: 42
  features:
    numeric:
      - "numeric_1"
    categorical:
      - "categorical_1"

training:
  test_size: 0.2
  random_state: 42
  cv_folds: 5
  scoring: "accuracy"

mlflow:
  experiment_name: "nappecast"
  default_tracking_uri: "https://ronan-guillou-mlflow-test.hf.space/"
  registered_model_name: "nappecast_model"
  model_alias: "champion"  # Alias assigné à la dernière version entraînée (ex: "champion") depuis la version 2.9
