api:
  water:
    provider: "hubeau"
    url_station: "https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/stations"
    url_piezometre: "https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/chroniques"
    code_bss: 
      - "10906X0039/C2-1"
  weather:
    provider: "open-meteo"
    url_archive: "https://archive-api.open-meteo.com/v1/archive"
    url_forecast: ""
    start_date: "2017-01-01"
    