services:
  mlflow:
    image: 844099234486.dkr.ecr.eu-west-3.amazonaws.com/mlflow:latest
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlflow-data
    env_file:
      - .env.runtime
      - mlflow.env
    restart: unless-stopped

volumes:
  mlflow_data: