services:
  caddy:
    image: caddy:2
    container_name: caddy
    env_file: [appapi.env, .env.runtime]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    depends_on:
      - streamlit
    restart: unless-stopped

  streamlit:
    image: 844099234486.dkr.ecr.eu-west-3.amazonaws.com/streamlit:latest
    env_file: [appapi.env, .env.runtime]
    expose:
      - "8501"
    environment:
      - API_URL=http://api:8000
    volumes:
      - streamlit_data:/home/app/data/streamlit
    restart: unless-stopped

  api:
    image: 844099234486.dkr.ecr.eu-west-3.amazonaws.com/appapi:latest
    env_file: [appapi.env, .env.runtime]
    volumes:
      - ./logs:/home/app/logs
    environment:
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
      - PIPELINE_SECRET=${PIPELINE_SECRET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  streamlit_data:
  caddy_data: