name: ci-app_api

on:
  # push:
    # branches: [main, develop]
  # pull_request:
    # branches: [main]
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:

      # Étape 1 — cloner le repo sur la machine virtuelle
      - name: Checkout
        uses: actions/checkout@v4

      # Étape 2 — installer Python 3.13 sur la machine virtuelle
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      # Étape 3 — installer les dépendances du projet
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Étape 4 — lancer les tests
      # -v        : verbose, affiche le nom de chaque test
      # --tb=short : en cas d'échec, affiche un traceback condensé
      - name: Run tests
        run: pytest tests/ -v --tb=short

      # Étape 5 — se connecter à DockerHub
      # Avant le build : nécessaire si la base image est privée
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Étape 6 — builder l'image Docker
      # -f  : chemin vers le Dockerfile (pas à la racine du repo)
      # .   : contexte de build = racine du repo
      # Deux tags : SHA immuable (rollback) + latest (pointeur courant)
      - name: Build Docker image
        run: |
          docker build -f src/api/Dockerfile \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/nappecast-api:${{ github.sha }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/nappecast-api:latest \
            .

      # Étape 7 — pusher les deux tags sur DockerHub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nappecast-api:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nappecast-api:latest
      
      # Étape 8 — redéployment du conteneur API à partir de la nouvelle image build
      # appleboy/ssh-action: action officielle pour exécutetr des commandes ssh
      - name: Deploy to EC2_APP
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_APP_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/app/docker/app-api  # chemin du repo sur l'EC2 AWS
            docker compose pull                   # récupération de la nouvelle image buildé depuis DockerHub
            docker compose up -d --no-build       # redémarrage des conteneurs en arrière-plan
            docker image prune -f                 # nettoie les anciennes images
